FROM ghcr.io/davidsaemund/vispfrankareal:latest
LABEL Name=vispfrankareal Version=0.0.1
RUN apt-get update 

RUN apt-get install -y  \
    build-essential \
    cmake \
    git \
    libpoco-dev \
    libeigen3-dev \
    libssl-dev \
    libusb-1.0-0-dev \
    pkg-config \
    libgtk-3-dev \
    cmake-curses-gui \
    libglfw3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libudev-dev \
    sudo